# Generated by Django 5.1.6 on 2025-02-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_details', '0002_alter_orderdetails_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='plato_nombre',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
