# Generated by Django 5.1.5 on 2025-02-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="plato",
            name="alergenos",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="plato",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plato",
            name="imagen",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plato",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plato",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platos",
                to="menu.categoria",
            ),
        ),
    ]
