# Generated by Django 5.1.5 on 2025-02-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_categoria_plato_alergenos_plato_cantidad_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plato",
            old_name="categoria",
            new_name="categoría",
        ),
        migrations.AlterField(
            model_name="plato",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
    ]
