# Generated by Django 5.1.5 on 2025-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_rename_categoria_plato_categoría_alter_plato_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="plato",
            name="nickname",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
