# Generated by Django 5.1.6 on 2025-02-27 13:47
# Generated by Django 5.1.6 on 2025-02-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_plato_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='categoría',
            new_name='categoria',
        ),
    ]
